apiVersion: apps.example.com/v1alpha1
kind: DemoApp
metadata:
  name: my-demoapp
  namespace: default
spec:
  foo: "example-foo-value"
  deployments:
    - name: frontend
      replicas: 2
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      containers:
        - name: frontend-container
          image: nginx:latest
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
    - name: backend
      replicas: 1
      strategy:
        type: Recreate
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      containers:
        - name: backend-container
          image: paulbouwer/hello-kubernetes:1.10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15

